// <auto-generated />
using System;
using DataQuillDesktop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataQuillDesktop.Migrations
{
    [DbContext(typeof(QuillDbContext))]
    [Migration("20250921014040_AddDataSources")]
    partial class AddDataSources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataQuillDesktop.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppConfigs");
                });

            modelBuilder.Entity("DataQuillDesktop.Models.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("InterfaceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("DataQuillDesktop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataQuillDesktop.Models.DataSource", b =>
                {
                    b.OwnsOne("DataQuillDesktop.Models.DataSourceConfiguration", "Configuration", b1 =>
                        {
                            b1.Property<int>("DataSourceId")
                                .HasColumnType("integer");

                            b1.Property<string>("ApiKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("BaudRate")
                                .HasColumnType("integer");

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomParameters")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("DataBits")
                                .HasColumnType("integer");

                            b1.Property<string>("Endpoint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FilePattern")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Handshake")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Host")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Parity")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Port")
                                .HasColumnType("integer");

                            b1.Property<string>("PortName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RetryAttempts")
                                .HasColumnType("integer");

                            b1.Property<int>("SlaveId")
                                .HasColumnType("integer");

                            b1.Property<string>("StopBits")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Timeout")
                                .HasColumnType("integer");

                            b1.Property<string>("Topic")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("UseSSL")
                                .HasColumnType("boolean");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("WatchForChanges")
                                .HasColumnType("boolean");

                            b1.HasKey("DataSourceId");

                            b1.ToTable("DataSources");

                            b1.WithOwner()
                                .HasForeignKey("DataSourceId");
                        });

                    b.Navigation("Configuration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
